let mapleader=" " "将leader键（\）设置为空格键
syntax on "代码高亮
set number "设置行号
set norelativenumber "关闭相对行号
set cursorline "设置光标下划线
set wrap "使键入内容不会超出屏幕边界（相当于换行）
set showcmd "命令展示
set wildmenu "提示
set hlsearch "搜索高亮
set incsearch "一边输入一边高亮
exec "nohlsearch"
set ignorecase "搜索时忽略大小写
set smartcase "搜索时智能大小写

noremap u l "以u代替l
noremap l u "以u代替l
noremap <LEADER><CR> :nohlsearch<CR> "按下空格加回车取消搜索结果高亮显示

map s <nop> "按下s不做任何操作（本来应该是按下s删除当前字符并进入插入模式）
map S :w<CR> "按下S保存
map Q :q<CR> "按下Q退出
map R :source $MYVIMRC<CR> "按下R自动刷新配置文件

"插件安装
call plug#begin('~/.vim/plugged')

Plug 'vim-airline/vim-airline' "状态栏插件
Plug 'neoclide/coc.nvim',{'branch': 'release'} "代码补全插件
Plug 'preservim/nerdtree' "nerdtree是一个树形的目录管理插件，可以方便在nvim中进行当前文件夹中的文件切换
Plug 'Xuyuanp/nerdtree-git-plugin' "显示git状态标志的NERDTree插件


call plug#end()

let g:coc_disable_startup_warning = 1

"molokai配色方案
"color molokai
"配色方案设置
"let g:molokai_original = 1
"let g:rehash256 = 1
"set background=light "配色方案背景设置

"gruvbox配色方案
color gruvbox
set background=dark

"nerdtree设置
autocmd vimenter * NERDTree "启动vim时自动打开tree结构
"未指定具体文件打开tree结构
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
"修改目录图标
let g:NERDTreeDirArrowExpandable = '+'
let g:NERDTreeDirArrowCollapsible = '-'
"显示隐藏文件
"let NERDTreeShowHidden=1



"常用操作：
"p:粘贴。
"y:复制。
"d:删除。
"c:改变。
"f:查找。
"split:上下分屏
"vsplit:左右分屏
"o:当前光标行下面插入空行并进入插入模式
"大写O:前光标行上面插入空行并进入插入模式
